export const MEDIUM_PRESET_OPTIONS = [
  "Oil on canvas",
  "Oil on panel",
  "Oil stick on paper",
  "Silk screen on paper",
  "Acrylic on canvas",
  "Acrylic on panel",
  "Watercolor on paper",
  "Gouache on paper",
  "Ink on paper",
  "Charcoal on paper",
  "Graphite on paper",
  "Pastel on paper",
  "Colored pencil on paper",
  "Mixed media on paper",
  "Mixed media on panel",
  "Collage on paper",
  "Printmaking on paper",
  "Digital print on paper",
  "Photography (archival pigment print)",
  "Encaustic on panel",
  "Tempera on panel",
] as const;
